sudo: required
language: python
cache: pip
python:
- '3.6'
services:
- docker
- redis-server
addons:
  postgresql: '9.6'
  hosts:
  - redis
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.16.1
  - DATABASE_URL=postgres:///localhost:5432/postgres?user=postgres
  - ANSIBLE_HOST_KEY_CHECKING=False
  - ANSIBLE_VAULT_PASSWORD_FILE=.vault_password.txt
  - REDIS_URL=redis://localhost:6379/0
  - CACHE_REDIS_LOCATION=redis://redis:6379/0
  - CHANNELS_REDIS_LOCATION=redis://redis:6379/1
  - CELERY_BROKER_URL=redis://redis:6379/2
  - CELERY_BROKER_BACKEND=redis://redis:6379/3
  - secure: R3OXIF36VY8OXK+J/gddNFw8WP3CoyuwhpRiCGFtIPOlP5z+MkFhkfktzsMjAXI+NMTh+BQm8SFPInULtgko20mbqy7djhZBOM4xsmr7MFbn+pMPHCjUUNbJ8JDbRV9wU52nDWKLW3G05bvFBrN3433j6hhvByAbnmhzYA4Vekm+wyVOy4V5kG9L5LimbrjAtP08hMZ0beXLP1noh+pteC2v6VtzMkW0bZrcx6BAyfeNmrDUYaVW7EXwsx/H2xvRWzSiPqvj5e/mvS5ocBE+4HNaWjw7na5liETa17CkAerSjNcpaP9TqgS5G1TGjA7+EVnoDnQMXm3XwwI/Ciscte8XND6x8+Z52m7uNAR6nnITVbsRU/HtXd8VUIj+5wIkLGyA5vjUmZG5wHgf7yuTtM/4sXZQY9/vEKmQTLSpBX14AWAZa5ODRVpk8vT5idmvsYH9ewUQbFa47MCGolcRTCCI4ljokKac+VNMgKLG48yvKFrXKLnAQhaUiIDJ3zYV2gHkixCFOTEzdt4UsPbYtE74BFuuy+edEPNvJmG0YCaUYiLiZJXHpGg27Bbr3bSPY4tojjGW7ItbNMRYeEi5ONwyg7gT94U6m6CXcWx4nzBWKi5PuuNlaGSml3YQ/14HoSuEJKDWkTX+0AJNuAqEHiPj+D8b8c1svo4sKzQo5B8=
  - secure: hpGPydnvMJZbQqQ+fx13Cao/zFZwkDUs2aCErRXgCXtOEy13H/8qQrP8IWht2tyF0Pm1IPmoNCWvUdlO37KfapUklS/BCL1H3GLLA2zmTOaOonYJw0LRQNJiJWu+fWVQOCf2+cEf75NZCYd6vUssmXHoQf+R0JmrhK3sV1TbpaIQKdp6UNVLJdJRCh0w9rpb4JO1glgKNAZ+evZCGvDoaCf5AnoWMc6rRZhAZWT3zmKf6/79GwGwGQW1S3b7PqfC44zklQbVrpn/dXvyLUrarB0ors9Ogo4dlu6Eswkdz1qPpekRr1WyZ31cPLFByEnRdUVtEDlCv1Avx6c0Z6+1wwhS0ULQEzEYql4FOdAGkAxS8MSlTvpzKUazEd4ZW/OaxcPdbVHV2evxN8tf9/Sgjw4i8kIOIHz3N3GAaHfdhf4ESHRNl0gglrVlLNf+45kWNBVpD2Eg93Njh5Nnoa+53gS7CxfThMotSVjZDzdNTAPe0nSLRl8jadkOAxk7k0iSOpioAGJ4dyEIdCz+gQqd4WaI5SWtCClhFvU2w2rveflv+ijBNHuRZ7DLx1dkNexGt8EePYCMMvbpTJlJCVqCEQnEUzQrUk2t+XwxR/jdN4ABpOG/kLaUxmBlyXh+hct88+S9EDzYwIHWRFw2PIvNlPjYs+2guqezIBYDQh85D6c=
branches:
  only:
  - base
  except:
  - master
before_install: "./before_install.sh"
install:
- pip install pipenv
- pipenv install
script:
- py.test
- docker-compose build
- "./deploy/scripts/git-merge-push.sh"
after_success:
- echo "Build success!"
after_failure:
- echo "Build failure!"
before_deploy:
- "./deploy/scripts/git-merge-push.sh"
deploy:
  provider: script
  script: "./deploy/scripts/deploy.sh"
  on:
    all_branches: true
